### ISSUE TITLE
NC state. Diagrams for Paul Rs most recent manuscript

### ISSUE THREAD

**Issue by tdube2014** [tdube2014/tasks#12]
Design and illustrate 4 diagrams for Pauls most recent manuscript. Draft to be given to Jeff beginning of January.

**Comment by tdube2014** [comment]
Illustrations completed.

**Comment by bletcher** [comment]
If done, you can close the issue.

On Fri, Jan 22, 2016 at 3:46 PM, tdube2014 notifications@github.com wrote:

> Illustrations completed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tdube2014/tasks/issues/12#issuecomment-174041756.

## 

 Silvio O. Conte Anadromous Fish Research Center, U.S. Geological Survey
 P.O. Box 796 -- One Migratory Way
 Turners Falls, MA 01376
 (413) 863-3803
 Cell: (413) 522-9417
 FAX (413) 863-9810

ben_letcher@usgs.gov
bletcher@eco.umass.edu
http://www.lsc.usgs.gov/?q=cafb-research

**Comment by tdube2014** [comment]
ok
